os: linux
dist: xenial
sudo: required
language: csharp
mono: none
dotnet: 2.2
script:
 - dotnet restore ./ImeWlConverterDotnetCore/ImeWlConverterCmd
 - dotnet build ./ImeWlConverterDotnetCore/ImeWlConverterCmd
 - dotnet test ./ImeWlConverterDotnetCore/ImeWlConverterCmdTest
